version: '3.9'
services:
  db:
    build: ./db
    ports:
      - ${DB_PORT}:5432
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_LOGIN}
      - POSTGRES_DB=${DB_NAME}